-- Add language table

USE ${schemaName};

CREATE TABLE IF NOT EXISTS language (
  id smallint NOT NULL PRIMARY KEY,
  code char(3) NOT NULL UNIQUE   COMMENT 'CEDS / ISO 639-2 code',
  altcode char(2) NULL           COMMENT 'optional CALPADS code',
  name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS staging_language (
  id smallint NOT NULL PRIMARY KEY,
  code char(3) NOT NULL,
  altcode char(2) NULL,
  name varchar(100) NOT NULL
);

-- Have to duplicate this so we can update the exam table using it
INSERT INTO language (id, code, altcode, name) VALUES
(404, 'aar', NULL, 'Afar'),
(464, 'abk', NULL, 'Abkhazian'),
(80,  'ace', NULL, 'Achinese'),
(233, 'ach', NULL, 'Acoli'),
(135, 'ada', NULL, 'Adangme'),
(352, 'ady', NULL, 'Adyghe; Adygei'),
(54,  'afa', '54', 'Afro-Asiatic languages; Chaldean'),
(207, 'afh', NULL, 'Afrihili'),
(286, 'afr', NULL, 'Afrikaans'),
(248, 'ain', NULL, 'Ainu'),
(175, 'aka', NULL, 'Akan'),
(185, 'akk', NULL, 'Akkadian'),
(56,  'alb', '56', 'Albanian'),
(14,  'ale', NULL, 'Aleut'),
(118, 'alg', NULL, 'Algonquian languages'),
(16,  'alt', NULL, 'Southern Altai'),
(66,  'amh', '66', 'Amharic'),
(152, 'ang', NULL, 'English, Old (ca.450-1100)'),
(166, 'anp', NULL, 'Angika'),
(75,  'apa', NULL, 'Apache languages'),
(11,  'ara', '11', 'Arabic'),
(179, 'arc', NULL, 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'),
(181, 'arg', NULL, 'Aragonese'),
(12,  'arm', '12', 'Armenian'),
(195, 'arn', NULL, 'Mapudungun; Mapuche'),
(198, 'arp', NULL, 'Arapaho'),
(204, 'art', NULL, 'Artificial languages'),
(342, 'arw', NULL, 'Arawak'),
(366, 'asm', NULL, 'Assamese'),
(395, 'ast', NULL, 'Asturian; Bable; Leonese; Asturleonese'),
(31,  'ath', NULL, 'Athapascan languages'),
(430, 'aus', NULL, 'Australian languages'),
(449, 'ava', NULL, 'Avaric'),
(441, 'ave', NULL, 'Avestan'),
(460, 'awa', NULL, 'Awadhi'),
(73,  'aym', NULL, 'Aymara'),
(381, 'aze', NULL, 'Azerbaijani'),
(457, 'bad', NULL, 'Banda languages'),
(76,  'bai', NULL, 'Bamileke languages'),
(355, 'bak', NULL, 'Bashkir'),
(350, 'bal', NULL, 'Baluchi'),
(418, 'bam', NULL, 'Bambara'),
(169, 'ban', NULL, 'Balinese'),
(477, 'baq', NULL, 'Basque'),
(363, 'bas', NULL, 'Basa'),
(52,  'bat', '52', 'Baltic languages'),
(246, 'bej', NULL, 'Beja; Bedawiyet'),
(268, 'bel', NULL, 'Belarusian'),
(337, 'bem', NULL, 'Bemba'),
(61,  'ben', '61', 'Bengali'),
(242, 'ber', NULL, 'Berber languages'),
(421, 'bho', NULL, 'Bhojpuri'),
(440, 'bih', NULL, 'Bihari languages'),
(272, 'bik', NULL, 'Bikol'),
(55,  'bin', NULL, 'Bini; Edo'),
(139, 'bis', NULL, 'Bislama'),
(433, 'bla', NULL, 'Siksika'),
(58,  'bnt', NULL, 'Bantu (Other)'),
(59,  'bos', NULL, 'Bosnian'),
(401, 'bra', NULL, 'Braj'),
(275, 'bre', NULL, 'Breton'),
(424, 'btk', NULL, 'Batak languages'),
(422, 'bua', NULL, 'Buriat'),
(276, 'bug', NULL, 'Buginese'),
(67,  'bul', '67', 'Bulgarian'),
(13,  'bur', '13', 'Burmese'),
(215, 'byn', NULL, 'Blin; Bilin'),
(226, 'cad', NULL, 'Caddo'),
(217, 'cai', NULL, 'Central American Indian languages'),
(416, 'car', NULL, 'Galibi Carib'),
(482, 'cat', NULL, 'Catalan; Valencian'),
(461, 'cau', NULL, 'Caucasian languages'),
(36,  'ceb', '36', 'Cebuano; Visayan'),
(74,  'cel', NULL, 'Celtic languages'),
(20,  'cha', '20', 'Chamorro'),
(39,  'chz', '39', 'Chaozhou; Chiuchow; Teochew'),  -- code is unofficial
(77,  'chb', NULL, 'Chibcha'),
(78,  'che', NULL, 'Chechen'),
(79,  'chg', NULL, 'Chagatai'),
(3,   'chi', '03', 'Chinese; Cantonese'),
(81,  'chk', NULL, 'Chuukese'),
(82,  'chm', NULL, 'Mari'),
(83,  'chn', NULL, 'Chinook jargon'),
(84,  'cho', NULL, 'Choctaw'),
(85,  'chp', NULL, 'Chipewyan; Dene Suline'),
(86,  'chr', NULL, 'Cherokee'),
(87,  'chu', NULL, 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
(88,  'chv', NULL, 'Chuvash'),
(89,  'chy', NULL, 'Cheyenne'),
(90,  'cmc', NULL, 'Chamic languages'),
(91,  'cnr', NULL, 'Montenegrin'),
(92,  'cop', NULL, 'Coptic'),
(93,  'cor', NULL, 'Cornish'),
(94,  'cos', NULL, 'Corsican'),
(95,  'cpe', NULL, 'Creoles and pidgins, English based'),
(96,  'cpf', NULL, 'Creoles and pidgins, French-based '),
(97,  'cpp', NULL, 'Creoles and pidgins, Portuguese-based '),
(98,  'cre', NULL, 'Cree'),
(285, 'crh', NULL, 'Crimean Tatar; Crimean Turkish'),
(100, 'crp', NULL, 'Creoles and pidgins '),
(101, 'csb', NULL, 'Kashubian'),
(102, 'cus', NULL, 'Cushitic languages'),
(103, 'cze', NULL, 'Czech'),
(104, 'dak', NULL, 'Dakota'),
(105, 'dan', NULL, 'Danish'),
(106, 'dar', NULL, 'Dargwa'),
(107, 'day', NULL, 'Land Dayak languages'),
(108, 'del', NULL, 'Delaware'),
(109, 'den', NULL, 'Slave (Athapascan)'),
(110, 'dgr', NULL, 'Dogrib'),
(111, 'din', NULL, 'Dinka'),
(112, 'div', NULL, 'Divehi; Dhivehi; Maldivian'),
(113, 'doi', NULL, 'Dogri'),
(114, 'dra', NULL, 'Dravidian languages'),
(115, 'dsb', NULL, 'Lower Sorbian'),
(116, 'dua', NULL, 'Duala'),
(117, 'dum', NULL, 'Dutch, Middle (ca.1050-1350)'),
(15,  'dut', '15', 'Dutch'),
(119, 'dyu', NULL, 'Dyula'),
(120, 'dzo', NULL, 'Dzongkha'),
(121, 'efi', NULL, 'Efik'),
(122, 'egy', NULL, 'Egyptian (Ancient)'),
(123, 'eka', NULL, 'Ekajuk'),
(124, 'elx', NULL, 'Elamite'),
(0,   'eng', '00', 'English'),
(126, 'enm', NULL, 'English, Middle (1100-1500)'),
(127, 'epo', NULL, 'Esperanto'),
(128, 'est', NULL, 'Estonian'),
(129, 'ewe', NULL, 'Ewe'),
(130, 'ewo', NULL, 'Ewondo'),
(131, 'fan', NULL, 'Fang'),
(132, 'fao', NULL, 'Faroese'),
(133, 'fat', NULL, 'Fanti'),
(134, 'fij', NULL, 'Fijian'),
(5,   'fil', '05', 'Filipino; Pilipino'),
(136, 'fin', NULL, 'Finnish'),
(137, 'fiu', NULL, 'Finno-Ugrian languages'),
(138, 'fon', NULL, 'Fon'),
(17,  'fre', '17', 'French'),
(140, 'frm', NULL, 'French, Middle (ca.1400-1600)'),
(141, 'fro', NULL, 'French, Old (842-ca.1400)'),
(142, 'frr', NULL, 'Northern Frisian'),
(143, 'frs', NULL, 'Eastern Frisian'),
(144, 'fry', NULL, 'Western Frisian'),
(145, 'ful', NULL, 'Fulah'),
(146, 'fur', NULL, 'Friulian'),
(147, 'gaa', NULL, 'Ga'),
(148, 'gay', NULL, 'Gayo'),
(149, 'gba', NULL, 'Gbaya'),
(150, 'gem', NULL, 'Germanic languages'),
(151, 'geo', NULL, 'Georgian'),
(18,  'ger', '18', 'German'),
(153, 'gez', NULL, 'Geez'),
(154, 'gil', NULL, 'Gilbertese'),
(155, 'gla', NULL, 'Gaelic; Scottish Gaelic'),
(156, 'gle', NULL, 'Irish'),
(157, 'glg', NULL, 'Galician'),
(158, 'glv', NULL, 'Manx'),
(159, 'gmh', NULL, 'German, Middle High (ca.1050-1500)'),
(160, 'goh', NULL, 'German, Old High (ca.750-1050)'),
(161, 'gon', NULL, 'Gondi'),
(162, 'gor', NULL, 'Gorontalo'),
(163, 'got', NULL, 'Gothic'),
(164, 'grb', NULL, 'Grebo'),
(165, 'grc', NULL, 'Greek, Ancient (to 1453)'),
(19,  'gre', '19', 'Greek'),
(167, 'grn', NULL, 'Guarani'),
(168, 'gsw', NULL, 'Swiss German; Alemannic; Alsatian'),
(43,  'guj', '43', 'Gujarati'),
(170, 'gwi', NULL, 'Gwich\'in'),
(171, 'hai', NULL, 'Haida'),
(172, 'hat', NULL, 'Haitian; Haitian Creole'),
(173, 'hau', NULL, 'Hausa'),
(174, 'haw', NULL, 'Hawaiian'),
(21,  'heb', '21', 'Hebrew'),
(176, 'her', NULL, 'Herero'),
(177, 'hil', NULL, 'Hiligaynon'),
(178, 'him', NULL, 'Himachali languages; Western Pahari languages'),
(22,  'hin', '22', 'Hindi'),
(180, 'hit', NULL, 'Hittite'),
(23,  'hmn', '23', 'Hmong; Mong'),
(182, 'hmo', NULL, 'Hiri Motu'),
(183, 'hrv', NULL, 'Croatian'),
(184, 'hsb', NULL, 'Upper Sorbian'),
(24,  'hun', '24', 'Hungarian'),
(186, 'hup', NULL, 'Hupa'),
(187, 'iba', NULL, 'Iban'),
(188, 'ibo', NULL, 'Igbo'),
(189, 'ice', NULL, 'Icelandic'),
(190, 'ido', NULL, 'Ido'),
(191, 'iii', NULL, 'Sichuan Yi; Nuosu'),
(192, 'ijo', NULL, 'Ijo languages'),
(193, 'iku', NULL, 'Inuktitut'),
(194, 'ile', NULL, 'Interlingue; Occidental'),
(25,  'ilo', '25', 'Iloko; Ilocano'),
(196, 'ina', NULL, 'Interlingua (International Auxiliary Language Association)'),
(197, 'inc', NULL, 'Indic languages'),
(26,  'ind', '26', 'Indonesian'),
(199, 'ine', NULL, 'Indo-European languages'),
(200, 'inh', NULL, 'Ingush'),
(201, 'ipk', NULL, 'Inupiaq'),
(202, 'ira', NULL, 'Iranian languages'),
(203, 'iro', NULL, 'Iroquoian languages'),
(27,  'ita', '27', 'Italian'),
(205, 'jav', NULL, 'Javanese'),
(206, 'jbo', NULL, 'Lojban'),
(8,   'jpn', '08', 'Japanese'),
(208, 'jpr', NULL, 'Judeo-Persian'),
(209, 'jrb', NULL, 'Judeo-Arabic'),
(210, 'kaa', NULL, 'Kara-Kalpak'),
(211, 'kab', NULL, 'Kabyle'),
(212, 'kac', NULL, 'Kachin; Jingpho'),
(213, 'kal', NULL, 'Kalaallisut; Greenlandic'),
(214, 'kam', NULL, 'Kamba'),
(65,  'kan', '65', 'Kannada'),
(216, 'kar', NULL, 'Karen languages'),
(69,  'kas', '69', 'Kashmiri'),
(218, 'kau', NULL, 'Kanuri'),
(219, 'kaw', NULL, 'Kawi'),
(220, 'kaz', NULL, 'Kazakh'),
(221, 'kbd', NULL, 'Kabardian'),
(222, 'kha', NULL, 'Khasi'),
(223, 'khi', NULL, 'Khoisan languages'),
(224, 'khm', NULL, 'Central Khmer'),
(225, 'kho', NULL, 'Khotanese; Sakan'),
(68,  'kik', '68', 'Kikuyu; Gikuyu'),
(227, 'kin', NULL, 'Kinyarwanda'),
(228, 'kir', NULL, 'Kirghiz; Kyrgyz'),
(229, 'kmb', NULL, 'Kimbundu'),
(230, 'kok', NULL, 'Konkani'),
(231, 'kom', NULL, 'Komi'),
(232, 'kon', NULL, 'Kongo'),
(4,   'kor', '04', 'Korean'),
(234, 'kos', NULL, 'Kosraean'),
(235, 'kpe', NULL, 'Kpelle'),
(236, 'krc', NULL, 'Karachay-Balkar'),
(237, 'krl', NULL, 'Karelian'),
(238, 'kro', NULL, 'Kru languages'),
(239, 'kru', NULL, 'Kurukh'),
(240, 'kua', NULL, 'Kuanyama; Kwanyama'),
(241, 'kum', NULL, 'Kumyk'),
(51,  'kur', '51', 'Kurdish'),
(243, 'kut', NULL, 'Kutenai'),
(244, 'lad', NULL, 'Ladino'),
(245, 'lah', NULL, 'Lahnda'),
(47,  'lau', '47', 'Lahu'),  -- code is unofficial
(247, 'lam', NULL, 'Lamba'),
(10,  'lao', '10', 'Lao'),
(249, 'lat', NULL, 'Latin'),
(250, 'lav', NULL, 'Latvian'),
(251, 'lez', NULL, 'Lezghian'),
(252, 'lim', NULL, 'Limburgan; Limburger; Limburgish'),
(253, 'lin', NULL, 'Lingala'),
(254, 'lit', NULL, 'Lithuanian'),
(255, 'lol', NULL, 'Mongo'),
(256, 'loz', NULL, 'Lozi'),
(257, 'ltz', NULL, 'Luxembourgish; Letzeburgesch'),
(258, 'lua', NULL, 'Luba-Lulua'),
(259, 'lub', NULL, 'Luba-Katanga'),
(260, 'lug', NULL, 'Ganda'),
(261, 'lui', NULL, 'Luiseno'),
(262, 'lun', NULL, 'Lunda'),
(263, 'luo', NULL, 'Luo (Kenya and Tanzania)'),
(264, 'lus', NULL, 'Lushai'),
(265, 'mac', NULL, 'Macedonian'),
(266, 'mad', NULL, 'Madurese'),
(267, 'mag', NULL, 'Magahi'),
(48,  'mah', '48', 'Marshallese'),
(269, 'mai', NULL, 'Maithili'),
(270, 'mak', NULL, 'Makasar'),
(271, 'mal', NULL, 'Malayalam'),
(7,   'mnd', '07', 'Mandarin'),  -- code is unofficial
(273, 'man', NULL, 'Mandingo'),
(274, 'mao', NULL, 'Maori'),
(50,  'map', '50', 'Austronesian languages; Khmu'),
(64,  'mar', '64', 'Marathi'),
(277, 'mas', NULL, 'Masai'),
(278, 'may', NULL, 'Malay'),
(279, 'mdf', NULL, 'Moksha'),
(280, 'mdr', NULL, 'Mandar'),
(281, 'men', NULL, 'Mende'),
(282, 'mga', NULL, 'Irish, Middle (900-1200)'),
(283, 'mic', NULL, 'Mi\'kmaq; Micmac'),
(284, 'min', NULL, 'Minangkabau'),
(99,  'mis', '99', 'Uncoded languages'),
(9,   'mkh', '09', 'Mon-Khmer languages'),
(287, 'mlg', NULL, 'Malagasy'),
(288, 'mlt', NULL, 'Maltese'),
(289, 'mnc', NULL, 'Manchu'),
(290, 'mni', NULL, 'Manipuri'),
(291, 'mno', NULL, 'Manobo languages'),
(292, 'moh', NULL, 'Mohawk'),
(293, 'mon', NULL, 'Mongolian'),
(294, 'mos', NULL, 'Mossi'),
(295, 'mul', NULL, 'Multiple languages'),
(296, 'mun', NULL, 'Munda languages'),
(297, 'mus', NULL, 'Creek'),
(298, 'mwl', NULL, 'Mirandese'),
(299, 'mwr', NULL, 'Marwari'),
(300, 'myn', NULL, 'Mayan languages'),
(301, 'myv', NULL, 'Erzya'),
(302, 'nah', NULL, 'Nahuatl languages'),
(303, 'nai', NULL, 'North American Indian languages'),
(304, 'nap', NULL, 'Neapolitan'),
(305, 'nau', NULL, 'Nauru'),
(306, 'nav', NULL, 'Navajo; Navaho'),
(307, 'nbl', NULL, 'Ndebele, South; South Ndebele'),
(308, 'nde', NULL, 'Ndebele, North; North Ndebele'),
(309, 'ndo', NULL, 'Ndonga'),
(310, 'nds', NULL, 'Low German; Low Saxon; German, Low; Saxon, Low'),
(311, 'nep', NULL, 'Nepali'),
(312, 'new', NULL, 'Nepal Bhasa; Newari'),
(313, 'nia', NULL, 'Nias'),
(314, 'nic', NULL, 'Niger-Kordofanian languages'),
(315, 'niu', NULL, 'Niuean'),
(316, 'nno', NULL, 'Norwegian Nynorsk; Nynorsk, Norwegian'),
(317, 'nob', NULL, 'Bokmål, Norwegian; Norwegian Bokmål'),
(318, 'nog', NULL, 'Nogai'),
(319, 'non', NULL, 'Norse, Old'),
(320, 'nor', NULL, 'Norwegian'),
(321, 'nqo', NULL, 'N\'Ko'),
(322, 'nso', NULL, 'Pedi; Sepedi; Northern Sotho'),
(323, 'nub', NULL, 'Nubian languages'),
(324, 'nwc', NULL, 'Classical Newari; Old Newari; Classical Nepal Bhasa'),
(325, 'nya', NULL, 'Chichewa; Chewa; Nyanja'),
(326, 'nym', NULL, 'Nyamwezi'),
(327, 'nyn', NULL, 'Nyankole'),
(328, 'nyo', NULL, 'Nyoro'),
(329, 'nzi', NULL, 'Nzima'),
(330, 'oci', NULL, 'Occitan (post 1500); Provençal'),
(331, 'oji', NULL, 'Ojibwa'),
(332, 'ori', NULL, 'Oriya'),
(333, 'orm', NULL, 'Oromo'),
(334, 'osa', NULL, 'Osage'),
(335, 'oss', NULL, 'Ossetian; Ossetic'),
(336, 'ota', NULL, 'Turkish, Ottoman (1500-1928)'),
(49,  'oto', '49', 'Otomian languages; Mixteco'),
(338, 'paa', NULL, 'Papuan languages'),
(339, 'pag', NULL, 'Pangasinan'),
(340, 'pal', NULL, 'Pahlavi'),
(341, 'pam', NULL, 'Pampanga; Kapampangan'),
(28,  'pan', '28', 'Panjabi; Punjabi'),
(343, 'pap', NULL, 'Papiamento'),
(344, 'pau', NULL, 'Palauan'),
(345, 'peo', NULL, 'Persian, Old (ca.600-400 B.C.)'),
(346, 'per', '16', 'Persian; Farsi'),
(347, 'phi', NULL, 'Philippine languages'),
(348, 'phn', NULL, 'Phoenician'),
(349, 'pli', NULL, 'Pali'),
(41,  'pol', '41', 'Polish'),
(351, 'pon', NULL, 'Pohnpeian'),
(6,   'por', '06', 'Portuguese'),
(353, 'pra', NULL, 'Prakrit languages'),
(354, 'pro', NULL, 'Provençal, Old (to 1500)'),
(40,  'pus', '40', 'Pushto; Pashto'),
(356, 'que', NULL, 'Quechua'),
(357, 'raj', NULL, 'Rajasthani'),
(358, 'rap', NULL, 'Rapanui'),
(359, 'rar', NULL, 'Rarotongan; Cook Islands Maori'),
(360, 'roa', NULL, 'Romance languages'),
(361, 'roh', NULL, 'Romansh'),
(362, 'rom', NULL, 'Romany'),
(45,  'rum', '45', 'Romanian; Moldavian; Moldovan'),
(364, 'run', NULL, 'Rundi'),
(365, 'rup', NULL, 'Aromanian; Arumanian; Macedo-Romanian'),
(29,  'rus', '29', 'Russian'),
(367, 'sad', NULL, 'Sandawe'),
(368, 'sag', NULL, 'Sango'),
(369, 'sah', NULL, 'Yakut'),
(370, 'sai', NULL, 'South American Indian (Other)'),
(371, 'sal', NULL, 'Salishan languages'),
(372, 'sam', NULL, 'Samaritan Aramaic'),
(373, 'san', NULL, 'Sanskrit'),
(374, 'sas', NULL, 'Sasak'),
(375, 'sat', NULL, 'Santali'),
(376, 'scn', NULL, 'Sicilian'),
(377, 'sco', NULL, 'Scots'),
(378, 'sel', NULL, 'Selkup'),
(379, 'sem', NULL, 'Semitic languages'),
(380, 'sga', NULL, 'Irish, Old (to 900)'),
(37,  'sgn', '37', 'Sign Languages'),
(382, 'shn', NULL, 'Shan'),
(383, 'sid', NULL, 'Sidamo'),
(384, 'sin', NULL, 'Sinhala; Sinhalese'),
(385, 'sio', NULL, 'Siouan languages'),
(386, 'sit', NULL, 'Sino-Tibetan languages'),
(387, 'sla', NULL, 'Slavic languages'),
(388, 'slo', NULL, 'Slovak'),
(389, 'slv', NULL, 'Slovenian'),
(390, 'sma', NULL, 'Southern Sami'),
(391, 'sme', NULL, 'Northern Sami'),
(392, 'smi', NULL, 'Sami languages'),
(393, 'smj', NULL, 'Lule Sami'),
(394, 'smn', NULL, 'Inari Sami'),
(30,  'smo', '30', 'Samoan'),
(396, 'sms', NULL, 'Skolt Sami'),
(397, 'sna', NULL, 'Shona'),
(398, 'snd', NULL, 'Sindhi'),
(399, 'snk', NULL, 'Soninke'),
(400, 'sog', NULL, 'Sogdian'),
(60,  'som', '60', 'Somali'),
(402, 'son', NULL, 'Songhai languages'),
(403, 'sot', NULL, 'Sotho, Southern'),
(1,   'spa', '01', 'Spanish'),
(405, 'srd', NULL, 'Sardinian'),
(406, 'srn', NULL, 'Sranan Tongo'),
(407, 'srp', NULL, 'Serbian'),
(408, 'srr', NULL, 'Serer'),
(409, 'ssa', NULL, 'Nilo-Saharan languages'),
(410, 'ssw', NULL, 'Swati'),
(411, 'suk', NULL, 'Sukuma'),
(412, 'sun', NULL, 'Sundanese'),
(413, 'sus', NULL, 'Susu'),
(414, 'sux', NULL, 'Sumerian'),
(415, 'swa', NULL, 'Swahili'),
(70,  'swe', '70', 'Swedish'),
(417, 'syc', NULL, 'Classical Syriac'),
(42,  'syr', '42', 'Syriac; Assyrian'),
(419, 'tah', NULL, 'Tahitian'),
(420, 'tai', NULL, 'Tai languages'),
(46,  'taw', '46', 'Taiwanese'),  -- code is unofficial
(63,  'tam', '63', 'Tamil'),
(423, 'tat', NULL, 'Tatar'),
(62,  'tel', '62', 'Telugu'),
(425, 'tem', NULL, 'Timne'),
(426, 'ter', NULL, 'Tereno'),
(427, 'tet', NULL, 'Tetum'),
(428, 'tgk', NULL, 'Tajik'),
(429, 'tgl', NULL, 'Tagalog'),
(32,  'tha', '32', 'Thai'),
(431, 'tib', NULL, 'Tibetan'),
(432, 'tig', NULL, 'Tigre'),
(57,  'tir', '57', 'Tigrinya'),
(434, 'tiv', NULL, 'Tiv'),
(435, 'tkl', NULL, 'Tokelau'),
(436, 'tlh', NULL, 'Klingon; tlhIngan-Hol'),
(437, 'tli', NULL, 'Tlingit'),
(438, 'tmh', NULL, 'Tamashek'),
(439, 'tog', NULL, 'Tonga (Nyasa)'),
(53,  'toi', '53', 'Toishanese'),  -- code is unofficial
(34,  'ton', '34', 'Tongan'),
(442, 'tpi', NULL, 'Tok Pisin'),
(443, 'tsi', NULL, 'Tsimshian'),
(444, 'tsn', NULL, 'Tswana'),
(445, 'tso', NULL, 'Tsonga'),
(446, 'tuk', NULL, 'Turkmen'),
(447, 'tum', NULL, 'Tumbuka'),
(448, 'tup', NULL, 'Tupi languages'),
(33,  'tur', '33', 'Turkish'),
(450, 'tut', NULL, 'Altaic languages'),
(451, 'tvl', NULL, 'Tuvalu'),
(452, 'twi', NULL, 'Twi'),
(453, 'tyv', NULL, 'Tuvinian'),
(454, 'udm', NULL, 'Udmurt'),
(455, 'uga', NULL, 'Ugaritic'),
(456, 'uig', NULL, 'Uighur; Uyghur'),
(38,  'ukr', '38', 'Ukrainian'),
(458, 'umb', NULL, 'Umbundu'),
(459, 'und', 'UU', 'Undetermined'),
(35,  'urd', '35', 'Urdu'),
(72,  'uzb', '72', 'Uzbek'),
(462, 'vai', NULL, 'Vai'),
(463, 'ven', NULL, 'Venda'),
(2,   'vie', '02', 'Vietnamese'),
(465, 'vol', NULL, 'Volapük'),
(466, 'vot', NULL, 'Votic'),
(467, 'wak', NULL, 'Wakashan languages'),
(468, 'wal', NULL, 'Walamo'),
(469, 'war', NULL, 'Waray'),
(470, 'was', NULL, 'Washo'),
(471, 'wel', NULL, 'Welsh'),
(472, 'wen', NULL, 'Sorbian languages'),
(473, 'wln', NULL, 'Walloon'),
(474, 'wol', NULL, 'Wolof'),
(475, 'xal', NULL, 'Kalmyk; Oirat'),
(476, 'xho', NULL, 'Xhosa'),
(44,  'yao', '44', 'Yao; Mien'),
(478, 'yap', NULL, 'Yapese'),
(479, 'yid', NULL, 'Yiddish'),
(480, 'yor', NULL, 'Yoruba'),
(481, 'ypk', NULL, 'Yupik languages'),
(71,  'zap', '71', 'Zapotec'),
(483, 'zbl', NULL, 'Blissymbols; Blissymbolics; Bliss'),
(484, 'zen', NULL, 'Zenaga'),
(485, 'zgh', NULL, 'Standard Moroccan Tamazight'),
(486, 'zha', NULL, 'Zhuang; Chuang'),
(487, 'znd', NULL, 'Zande languages'),
(488, 'zul', NULL, 'Zulu'),
(489, 'zun', NULL, 'Zuni'),
(490, 'zxx', NULL, 'No linguistic content; Not applicable'),
(491, 'zza', NULL, 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki');

-- create helper
DROP PROCEDURE IF EXISTS loop_by_exam_id;
DELIMITER //
CREATE PROCEDURE loop_by_exam_id(IN p_sql VARCHAR(1000))
BEGIN
  DECLARE batch, iter INTEGER;
  SET batch = 500000;
  SET iter = 0;

  SELECT 1 + FLOOR(MAX(id) / batch) INTO @max_iter FROM exam;

  partition_loop: LOOP
    SET @stmt = CONCAT(p_sql, ' AND e.id >= ', iter * batch, ' AND e.id < ', (iter + 1) * batch);
    PREPARE stmt FROM @stmt;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
    SELECT CONCAT('executed partition:', iter);

    SET iter = iter + 1;
    IF iter < @max_iter THEN
      ITERATE partition_loop;
    END IF;
    LEAVE partition_loop;
  END LOOP partition_loop;
END;
//
DELIMITER ;

-- do the work
-- unlike the warehouse, keep language_code and update it with the correct code value
CALL loop_by_exam_id('UPDATE exam e JOIN language l ON LOWER(e.language_code) = l.code SET e.language_code = l.code, e.updated = e.updated WHERE e.language_code IS NOT NULL');
CALL loop_by_exam_id('UPDATE exam e JOIN language l ON l.altcode IS NOT NULL AND e.language_code = l.altcode SET e.language_code = l.code, e.updated = e.updated WHERE e.language_code IS NOT NULL');

ALTER TABLE staging_exam
  ADD COLUMN language_id smallint NULL,
  DROP COLUMN language_code;

-- drop helper
DROP PROCEDURE loop_by_exam_id;
