USE datagen;

CREATE TABLE IF NOT EXISTS datagen.asmt_label_mapping (
  asmt_name varchar(255) NOT NULL,
  label varchar(255) NOT NULL
);

-- insert the mapping from assessment name to the cleaned up label
DELETE FROM datagen.asmt_label_mapping;
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-BriefWrites-ELA-11','High School ELA - Brief Writes (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-Editing-ELA-11','High School ELA - Editing (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-LangVocab-ELA-11','High School ELA - Language and Vocabulary Use (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-ListenInterpet-ELA-11','High School ELA - Listen/Interpret (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-Perf-Explanatory-Marshmallow','High School ELA Performance Task - How We Learn (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-ReadInfo-ELA-11','High School ELA - Read Informational Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-ReadLit-ELA-11','High School ELA - Read Literary Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-Research-ELA-11','High School ELA - Research (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11E-Revision-ELA-11','High School ELA - Revision (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-AlgLin','High School Math - Algebra and Functions I (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-AlgQuad','High School Math - Algebra and Functions II (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-GCO-MATH-11','High School Math - Geometry Congruence (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-GeoRightTriRatios-Calc-MATH-11','High School Math - Geometry and Right Triangle Trigonometry (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-GMD-MATH-11','High School Math - Geometry Measurement and Modeling (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-IF','High School Math - Interpreting Functions (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-NQ','High School Math - Number and Quantity (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-Perf-TeenDrivingRest-MATH-11','High School Math Performance Task - Teen Driving Restrictions (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-SP-Calc-MATH-11','High School Math - Statistics and Probability (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G11M-SSE','High School Math - Seeing Structure in Expressions/Polynomial Expressions (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-BriefWrites-ELA-3','Grade 03 ELA - Brief Writes (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-Editing-ELA-3','Grade 03 ELA - Editing (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-LangVocab-ELA-3','Grade 03 ELA - Language and Vocabulary Use (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-ListenInterpet-ELA-3','Grade 03 ELA - Listen/Interpret (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-Perf-Opinion-Beetles','Grade 03 ELA Performance Task - Beetles (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-ReadInfo-ELA-3','Grade 03 ELA - Read Informational Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-ReadLit-ELA-3','Grade 03 ELA - Read Literary Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-Research-ELA-3','Grade 03 ELA - Research (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3E-Revision-ELA-3','Grade 03 ELA - Revision (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3M-G-MATH-3','Grade 03 Math - Geometry (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3M-MD-MATH-3','Grade 03 Math - Measurement and Data (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3M-NBT-MATH-3','Grade 03 Math - Number and Operations in Base Ten (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3M-NF-MATH-3','Grade 03 Math - Number and Operations - Fractions (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3M-OA-MATH-3','Grade 03 Math - Operations and Algebraic Thinking (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G3M-Perf-OrderForm-MATH-3','Grade 03 Math Performance Task - Order Form (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-BriefWrites-ELA-4','Grade 04 ELA - Brief Writes (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-Editing-ELA-4','Grade 04 ELA - Editing (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-LangVocab-ELA-4','Grade 04 ELA - Language and Vocabulary Use (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-ListenInterpet-ELA-4','Grade 04 ELA - Listen/Interpret (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-Perf-Narrative-UnlikelyAnimal','Grade 04 ELA Performance Task - Unlikely Animal Friends (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-ReadInfo-ELA-4','Grade 04 ELA - Read Informational Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-ReadLit-ELA-4','Grade 04 ELA - Read Literary Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-Research-ELA-4','Grade 04 ELA - Research (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4E-Revision-ELA-4','Grade 04 ELA - Revision (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4M-G-MATH-4','Grade 04 Math - Geometry (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4M-MD-MATH-4','Grade 04 Math - Measurement and Data (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4M-NBT-MATH-4','Grade 04 Math - Number and Operations in Base Ten (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4M-NF-MATH-4','Grade 04 Math - Number and Operations - Fractions (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4M-OA-MATH-4','Grade 04 Math - Operations and Algebraic Thinking (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G4M-Perf-AnimalJumping-MATH-4','Grade 04 Math Performance Task - Animal Jumping (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-BriefWrites-ELA-5','Grade 05 ELA - Brief Writes (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-Editing-ELA-5','Grade 05 ELA - Editing (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-LangVocab-ELA-5','Grade 05 ELA - Language and Vocabulary Use (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-ListenInterpet-ELA-5','Grade 05 ELA - Listen/Interpret (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-Perf-Narrative-Whales','Grade 05 ELA Performance Task - Whales (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-ReadInfo-ELA-5','Grade 05 ELA - Read Informational Texts  (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-ReadLit-ELA-5','Grade 05 ELA - Read Literary Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-Research-ELA-5','Grade 05 ELA - Research (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5E-Revision-ELA-5','Grade 05 ELA - Revision (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5M-G-MATH-5','Grade 05 Math - Geometry (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5M-MD-MATH-5','Grade 05 Math - Measurement and Data (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5M-NBT-MATH-5','Grade 05 Math - Number and Operations in Base Ten (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5M-NF-MATH-5','Grade 05 Math - Number and Operations - Fractions (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5M-OA-MATH-5','Grade 05 Math - Operations and Algebraic Thinking (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G5M-Perf-TurtleHabitat-MATH-5','Grade 05 Math Performance Task - Turtle Habitat (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-BriefWrites-ELA-6','Grade 06 ELA - Brief Writes (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-Editing-ELA-6','Grade 06 ELA - Editing (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-LangVocab-ELA-6','Grade 06 ELA - Language and Vocabulary Use (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-ListenInterpet-ELA-6','Grade 06 ELA - Listen/Interpret (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-Perf-Argument-Multivitamins','Grade 06 ELA Performance Task - Multivitamins (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-ReadInfo-ELA-6','Grade 06 ELA - Read Informational Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-ReadLit-ELA-6','Grade 06 ELA - Read Literary Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-Research-ELA-6','Grade 06 ELA - Research (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6E-Revision-ELA-6','Grade 06 ELA - Revision (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6M-EE','Grade 06 Math - Expressions and Equations (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6M-G-Calc-MATH-6','Grade 06 Math - Geometry (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6M-NS','Grade 06 Math - The Number System (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6M-Perf-CellPhonePlan-MATH-6','Grade 06 Math Performance Task - Cell Phone Plan (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6M-RP','Grade 06 Math - Ratios and Proportional Relationships (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G6M-SP','Grade 06 Math - Statistics and Probability (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-BriefWrites-ELA-7','Grade 07 ELA - Brief Writes (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-Editing-ELA-7','Grade 07 ELA - Editing (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-LangVocab-ELA-7','Grade 07 ELA - Language and Vocabulary Use (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-ListenInterpet-ELA-7','Grade 07 ELA - Listen/Interpret (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-Perf-Explanatory-MobileEdTech','Grade 07 ELA Performance Task - Mobile Ed Technology (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-ReadInfo-ELA-7','Grade 07 ELA - Read Informational Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-ReadLit-ELA-7','Grade 07 ELA - Read Literary Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-Research-ELA-7','Grade 07 ELA - Research (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7E-Revision-ELA-7','Grade 07 ELA - Revision (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7M-EE','Grade 07 Math - Expressions and Equations (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7M-G','Grade 07 Math - Geometry (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7M-NS','Grade 07 Math - The Number System (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7M-Perf-CampingTasks-MATH-7','Grade 07 Math Performance Task - Camping Tasks (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7M-RP-Calc-MATH-7','Grade 07 Math - Ratios and Proportional Relationships (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G7M-SP-Calc-MATH-7','Grade 07 Math - Statistics and Probability (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8E-BriefWrites-ELA-8','Grade 08 ELA - Brief Writes (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8E-EditRevise-ELA-8','Grade 08 ELA - Edit/Revise (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8E-ListenInterpet-ELA-8','Grade 08 ELA - Listen/Interpret (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8E-Perf-Explanatory-CompareAncient','Grade 08 ELA Performance Task - Compare Ancient Societies (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8E-ReadInfo-ELA-8','Grade 08 ELA - Read Informational Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8E-ReadLit-ELA-8','Grade 08 ELA - Read Literary Texts (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8E-Research-ELA-8','Grade 08 ELA - Research (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8M-EE','Grade 08 Math - Expressions and Equations I (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8M-EE2-Calc-MATH-8','Grade 08 Math - Expressions and Equations II (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8M-F-Calc-MATH-8','Grade 08 Math - Functions (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8M-G-Calc-MATH-8','Grade 08 Math - Geometry (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8M-NS-MATH-8','Grade 08 Math - The Number System (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-IAB-FIXED-G8M-Perf-BaseballTickets-MATH-8','Grade 08 Math Performance Task - Baseball Tickets (IAB)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11E-COMBINED','High School ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11E-COMBINED-2017','High School ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11E-ELA-11','High School ELA Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11E-Perf-HowWeLearn','High School ELA Performance Task - How We Learn (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11M','High School Math Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11M-COMBINED','High School Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11M-COMBINED-2017','High School Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G11M-Perf-TeenDrivingRestricitons-MATH-11','High School Math Performance Task - Teen Driving Restrictions (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3E-COMBINED','Grade 03 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3E-COMBINED-2017','Grade 03 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3E-ELA-3','Grade 03 ELA Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3E-Perf-AnimalsWithShells','Grade 03 ELA Performance Task - Beetles (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3M-COMBINED','Grade 03 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3M-COMBINED-2017','Grade 03 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3M-MATH-3','Grade 03 Math Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G3M-Perf-OrderForm-MATH-3','Grade 03 Math Performance Task - Order Form (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4E-COMBINED','Grade 04 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4E-COMBINED-2017','Grade 04 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4E-ELA-4','Grade 04 ELA Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4E-Perf-UncommonAnimals','Grade 04 ELA Performance Task - Unlikely Animal Friends (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4M-COMBINED','Grade 04 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4M-COMBINED-2017','Grade 04 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4M-MATH-4','Grade 04 Math Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G4M-Perf-AnimalJumping-MATH-4','Grade 04 Math Performance Task - Animal Jumping (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5E-COMBINED','Grade 05 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5E-COMBINED-2017','Grade 05 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5E-ELA-5','Grade 05 ELA Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5E-Perf-MarineAnimal','Grade 05 ELA Performance Task - Whales (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5M-COMBINED','Grade 05 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5M-COMBINED-2017','Grade 05 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5M-MATH-5','Grade 05 Math Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G5M-Perf-TurtleHabitat-MATH-5','Grade 05 Math Performance Task - Turtle Habitat (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6E-COMBINED','Grade 06 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6E-COMBINED-2017','Grade 06 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6E-ELA-6','Grade 06 ELA Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6E-Perf-ImportanceOfNutrition','Grade 06 ELA Performance Task - Multivitamins (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6M','Grade 06 Math Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6M-COMBINED','Grade 06 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6M-COMBINED-2017','Grade 06 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G6M-Perf-CellPhonePlan-MATH-6','Grade 06 Math Performance Task - Cell Phone Plan (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7E-COMBINED','Grade 07 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7E-COMBINED-2017','Grade 07 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7E-ELA-7','Grade 07 ELA Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7E-Perf-TechnologyInTheClassroom','Grade 07 ELA Performance Task - Mobile Ed Technology (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7M','Grade 07 Math Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7M-COMBINED','Grade 07 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7M-COMBINED-2017','Grade 07 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G7M-Perf-CampingTasks-MATH-7','Grade 07 Math Performance Task - Camping Tasks (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8E-COMBINED','Grade 08 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8E-COMBINED-2017','Grade 08 ELA Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8E-ELA-8','Grade 08 ELA Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8E-Perf-CompareAncientSoc','Grade 08 ELA Performance Task - Compare Ancient Societies (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8M','Grade 08 Math Interim Test (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8M-COMBINED','Grade 08 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8M-COMBINED-2017','Grade 08 Math Interim Comprehensive (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SBAC-ICA-FIXED-G8M-Perf-BaseballTickets-MATH-8','Grade 08 Math Performance Task - Baseball Tickets (ICA)');
INSERT INTO datagen.asmt_label_mapping (asmt_name, label) VALUES ('SH-SBAC-IAB-Math-Student Help-11','Student Help for Math IAB');


-- make an import record for these changes
INSERT INTO warehouse.import (status, content, contentType, digest, batch)
VALUES (0, 2, 'text/plan', 'MANUAL', 'update assessment labels');
SELECT LAST_INSERT_ID() INTO @importid;

UPDATE warehouse.asmt a
JOIN datagen.asmt_label_mapping m on a.name=m.asmt_name
SET a.label = m.label, a.update_import_id=@importid;

-- trigger migration
UPDATE warehouse.import SET status = 1 WHERE id = @importid;
