-- CCS entries needed to load summatives

USE ${schemaName};

INSERT INTO common_core_standard ( subject_id, natural_id, description) VALUES
  (1,'3.G.A','Reason with shapes and their attributes.'),
  (1,'3.NF.A','Develop understanding of fractions as numbers.'),
  (1,'3.OA.A','Represent and solve problems involving multiplication and division.'),
  (1,'3.OA.B','Understand properties of multiplication and the relationship between multiplication and division.'),
  (1,'3.OA.D','Solve problems involving the four operations, and identify and explain patterns in arithmetic.'),
  (1,'4.G.A','Draw and identify lines and angles, and classify shapes by properties of their lines and angles.'),
  (1,'4.MD.A','Solve problems involving measurement and conversion of measurements.'),
  (1,'4.MD.B','Represent and interpret data.'),
  (1,'4.MD.C','Geometric measurement: understand concepts of angle and measure angles.'),
  (1,'4.NBT.A','Generalize place value understanding for multi-digit whole numbers.'),
  (1,'4.NBT.B','Use place value understanding and properties of operations to perform multi-digit arithmetic.'),
  (1,'4.NF.A','Extend understanding of fraction equivalence and ordering.'),
  (1,'4.NF.B','Build fractions from unit fractions.'),
  (1,'4.NF.C','Understand decimal notation for fractions, and compare decimal fractions.'),
  (1,'4.OA.A','Use the four operations with whole numbers to solve problems.'),
  (1,'4.OA.B','Gain familiarity with factors and multiples.'),
  (1,'4.OA.C','Generate and analyze patterns.'),
  (1,'5.MD.A','Convert like measurement units within a given measurement system.'),
  (1,'5.MD.B','Represent and interpret data.'),
  (1,'5.MD.C','Geometric measurement: understand concepts of volume.'),
  (1,'6.EE.A','Apply and extend previous understandings of arithmetic to algebraic expressions.'),
  (1,'6.EE.B','Reason about and solve one-variable equations and inequalities.'),
  (1,'6.EE.C','Represent and analyze quantitative relationships between dependent and independent variables.'),
  (1,'6.NS.A','Apply and extend previous understandings of multiplication and division to divide fractions by fractions.'),
  (1,'6.NS.B','Compute fluently with multi-digit numbers and find common factors and multiples.'),
  (1,'6.NS.C','Apply and extend previous understandings of numbers to the system of rational numbers.'),
  (1,'8.G.A','Understand congruence and similarity using physical models, transparencies, or geometry software.'),
  (1,'8.G.B','Understand and apply the Pythagorean Theorem.'),
  (1,'8.G.C','Solve real-world and mathematical problems involving volume of cylinders, cones, and spheres.'),
  (1,'8.NS.A','Know that there are numbers that are not rational, and approximate them by rational numbers.'),
  (1,'8.SP.A','Investigate patterns of association in bivariate data.'),
  (1,'A-APR.A','Perform arithmetic operations on polynomials.'),
  (1,'A-APR.B','Understand the relationship between zeros and factors of polynomials.'),
  (1,'A-APR.C','Use polynomial identities to solve problems.'),
  (1,'A-APR.D','Rewrite rational expressions.'),
  (1,'A-CED.A','Create equations that describe numbers or relationships.'),
  (1,'F-BF.A','Build a function that models a relationship between two quantities.'),
  (1,'F-BF.B','Build new functions from existing functions.'),
  (1,'F-LE.A','Construct and compare linear, quadratic, and exponential models and solve problems.'),
  (1,'F-LE.B','Interpret expressions for functions in terms of the situation they model.'),
  (1,'F-TF.A','Extend the domain of trigonometric functions using the unit circle.'),
  (1,'F-TF.B','Model periodic phenomena with trigonometric functions.'),
  (1,'F-TF.C','Prove and apply trigonometric identities.'),
  (1,'S-IC.A','Understand and evaluate random processes underlying statistical experiments.'),
  (1,'S-IC.B','Make inferences and justify conclusions from sample surveys, experiments, and observational studies.'),
  (1,'S-ID.A','Summarize, represent, and interpret data on a single count or measurement variable.'),
  (1,'S-ID.B','Summarize, represent, and interpret data on two categorical and quantitative variables.'),
  (1,'S-ID.C','Interpret linear models.'),
  (2,'3.L.4','Determine or clarify the meaning of unknown and multiple-meaning word and phrases based on grade 3 reading and content, choosing flexibly from a range of strategies.'),
  (2,'3.L.5','Demonstrate understanding of word relationships and nuances in word meanings.'),
  (2,'4.L.4','Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 4 reading and content, choosing flexibly from a range of strategies.'),
  (2,'4.L.5','Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.'),
  (2,'4.W.9','Draw evidence from literary or informational texts to support analysis, reflection, and research.'),
  (2,'5.L.4','Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 5 reading and content, choosing flexibly from a range of strategies.'),
  (2,'5.L.5','Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.'),
  (2,'5.W.9','Draw evidence from literary or informational texts to support analysis, reflection, and research.'),
  (2,'6.L.4','Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 6 reading and content, choosing flexibly from a range of strategies.'),
  (2,'6.L.5','Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.'),
  (2,'7.L.4','Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 7 reading and content, choosing flexibly from a range of strategies.'),
  (2,'7.L.5','Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.'),
  (2,'8.L.4','Determine or clarify the meaning of unknown and multiple-meaning words or phrases based on grade 8 reading and content, choosing flexibly from a range of strategies.'),
  (2,'8.L.5','Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.');






