CREATE TABLE fact_student_ica_exam_for_longitudinal (
  id bigint encode delta PRIMARY KEY,
  school_id integer encode raw NOT NULL,
  student_id bigint encode raw NOT NULL DISTKEY,
  asmt_id bigint encode raw  NOT NULL,
  grade_id smallint encode lzo NOT NULL,
  asmt_grade_id smallint encode lzo NOT NULL,
  school_year smallint encode raw NOT NULL,
  iep boolean encode raw NOT NULL,
  lep boolean encode raw NOT NULL,
  section504 boolean encode raw,
  economic_disadvantage boolean encode raw NOT NULL,
  migrant_status boolean encode raw,
  completeness_id smallint encode lzo NOT NULL,
  administration_condition_id smallint encode lzo NOT NULL,
  scale_score float encode bytedict ,
  scale_score_std_err float encode bytedict ,
  performance_level smallint encode lzo,
  claim1_scale_score float encode bytedict ,
  claim1_scale_score_std_err float encode bytedict ,
  claim1_category smallint encode lzo,
  claim2_scale_score float encode bytedict ,
  claim2_scale_score_std_err float encode bytedict ,
  claim2_category smallint encode lzo,
  claim3_scale_score float encode bytedict,
  claim3_scale_score_std_err float encode bytedict,
  claim3_category smallint encode lzo,
  claim4_scale_score float encode bytedict,
  claim4_scale_score_std_err float encode bytedict,
  claim4_category smallint encode lzo,
  completed_at timestamptz encode lzo NOT NULL,
  migrate_id bigint encode delta NOT NULL,
  update_import_id bigint encode delta NOT NULL,
  CONSTRAINT fk__fact_student_ica_exam_for_longitudinal__ica_asmt FOREIGN KEY(asmt_id) REFERENCES ica_asmt(id),
  CONSTRAINT fk__fact_student_ica_exam_for_longitudinal__school FOREIGN KEY(school_id) REFERENCES school(id),
  CONSTRAINT fk__fact_student_ica_exam_for_longitudinal__student FOREIGN KEY(student_id) REFERENCES student(id)
 )   COMPOUND SORTKEY (school_id, asmt_id);